baseUrl = "/"
languageCode = "en-us"
languageLang = "en"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  isMainsite = true
  mainsiteName = "bonfire.link"
  titleTagline = "assembling a decentralized tribe."

[menu]
  [[menu.main]]
    name = "NOTADAO"
    url = "https://notadao.bonfire.link"
  [[menu.main]]
    name = "TV"
    url = "https://tv.bonfire.link"
